### ISSUE TITLE
Automatically add binaries to release

### ISSUE THREAD

**Issue by jakobbraun** [exasol/parquet-edml-generator#22]
As of now, we have to upload the release artifacts from the CI build to the release.
It would be good to automate this.

**Comment by jakobbraun** [comment]
Maybe this can also be integrated into release-droid

**Comment by ckunki** [comment]
See also  repository [exasol/bucketfs-client](https://github.com/exasol/bucketfs-client), script [build-native-images.yml](https://github.com/exasol/bucketfs-client/blob/main/.github/workflows/build-native-images.yml), step [Upload binary](https://github.com/exasol/bucketfs-client/blob/85d20288e66e7b91b21a2c8a191c444ae3964310/.github/workflows/build-native-images.yml#L49).
