### ISSUE TITLE
Sign native binaries for macOS

### ISSUE THREAD

**Issue by kaklakariada** [exasol/parquet-edml-generator#36]
Starting with macOS version 13 Ventura binaries must be signed in order to execute them. That's why we removed support for macOS in PR #35.

The goal of this issue is to re-enable executing binaries on macOS. See also https://github.com/exasol/bucketfs-client/issues/26

## Workaround
Install a Java Runtime Environment on macOS and use the provided `.jar` file.

**Comment by ThomasBestfleisch** [comment]
Probably more a nice to have? It's not a real blocker for MacOS users as a workaround exists

**Comment by kaklakariada** [comment]
We don't have to capacity to implement this at the moment.
